package:
  name: cupti
  version: 10.2.89

source:
  path: .

build:
  number: 0

requirements:
  run:
    - cudatoolkit >=10.2,<10.3

about:
  home: https://developer.nvidia.com/cuda-toolkit
  license: proprietary - Nvidia
  license_family: Proprietary
  summary: 'development environment for GPU-accelerated applications, CUPTI components'
  description: |
    The NVIDIA CUDA Toolkit provides a comprehensive development environment
    for C and C++ developers building GPU-accelerated applications. The CUDA
    Toolkit ncludes a compiler for NVIDIA GPUs, math libraries, and tools for
    debugging and optimizing the performance of your applications.
  doc_url: https://docs.nvidia.com/cupti/index.html
